version: "3"

services:
  app:
    hostname: app
    container_name: api-go
    build: .
    command: go run main.go
    ports: 
      - 3000:3000
    volumes: 
      - .:/usr/app
    env_file:
      - .env
    depends_on:
      - "rabbitmq"
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: rabbitmq
    container_name: rabbitmq
    volumes:
      - ./docker_conf/rabbitmq/log:/var/log/rabbitmq
      - ./docker_conf/rabbitmq/data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    env_file:
      - .env
    labels:
      NAME: "rabbitmq"