version: "3.7"

services:
  app:
    container_name: api-go
    build: .
    command: go run main.go
    ports: 
      - 3000:3000
    volumes: 
     - .:/usr/app/test
    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    volumes:
      - ./docker_conf/rabbitmq/log:/var/log/rabbitmq
      - ./docker_conf/rabbitmq/data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    env_file:
      - .env
    networks:
        - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge