name: Go
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: | 
        rm -rf go.* vendor
        GO111MODULE=on go mod init github.com/igormpb/api-go-debts
        GO111MODULE=on go mod tidy
        GO111MODULE=on go get -v -u ./...
        GO111MODULE=on go mod vendor
          
